plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev' version "${neo_moddev}"
    id 'com.diffplug.spotless'
}

neoForge {
    neoFormVersion = "${neoform_version}"

    accessTransformers = ["../common/src/main/resources/META-INF/accesstransformer.cfg"]

    parchment {
        minecraftVersion = "${parchment_minecraft}"
        mappingsVersion = "${parchment_version}"
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    compileOnly "mod.azure.azurelib:azurelib-common-${minecraft_version}:${azurelib_version}"
    compileOnly "com.azure.azurecortex:azurecortex-common-${minecraft_version}:${azurecortex_version}"
    compileOnly "mod.azure.ovomorphosis:ovomorphosis-common-${minecraft_version}:${ovomorphosis_version}"
    compileOnly "io.github.llamalad7:mixinextras-common:0.3.5"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.5"
    compileOnly "maven.modrinth:gigeresque:0.8.16"
    compileOnly("com.avp.alien:avp_alien-neoforge-1.21.1:0.2.0-fork") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava(sourceSets.main.java.srcDirs.find { it.exists() })
    commonResources(sourceSets.main.resources.srcDirs.find { it.exists() })
}
