plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev' version "${neo_moddev}"
    id 'me.modmuss50.mod-publish-plugin' version "${modmuss50_mod_publish_version}"
    id 'com.diffplug.spotless'
}

neoForge {
    version = "${neo_version}"
    accessTransformers = ["../common/src/main/resources/META-INF/accesstransformer.cfg"]

    parchment {
        minecraftVersion = "${parchment_minecraft}"
        mappingsVersion = "${parchment_version}"
    }

    runs {
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            programArgument '--nogui'
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "mod.azure.azurelib:azurelib-neo-${minecraft_version}:${azurelib_version}"
    implementation "mod.azure.ovomorphosis:ovomorphosis-neoforge-${minecraft_version}:${ovomorphosis_version}"
    jarJar(implementation("com.azure.azurecortex:azurecortex-neoforge-${minecraft_version}:${azurecortex_version}")) {
        version {
            strictly "[${azurecortex_version}]"
            prefer azurecortex_version
        }
    }
    implementation "maven.modrinth:gigeresque:0.8.16"
    compileOnly("com.avp.alien:avp_alien-neoforge-1.21.1:0.2.0-fork") {
        exclude group: 'org.slf4j', module: 'slf4j-api'
    }
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        def jarFile = file("build/libs/pathogenesis-neoforge-${minecraft_version}-${project.version}.jar")
        file = jarFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("neoforge")

        curseforge {
            projectId = project.curseforgeID
            projectSlug = project.projectSlug
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
            requires {
                slug = "ovomorphosis"
            }
            javaVersions.add(JavaVersion.VERSION_21)
            client = true
            server = true
        }
        modrinth {
            projectId = project.modrinthID
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
            requires {
                slug = "ovomorphosis"
            }
            environment = CLIENT_AND_SERVER
        }
    }
}
